language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm@6.14.8
  - npm install expo-cli
  - npm install serve
install:
  - npm install
script:
  - expo build:web
  - echo $(ls)
deploy:
  local_dir: 
  provider: pages:git
  edge: true 
  cleanup: false
  token: $PAGES_TOKEN 
  keep_history: true
  target_branch: main
  on:
    branch: main
