export class NavigationRoutes {
    static ROUTE_HOME = "ROUTE_HOME";
    static ROUTE_LOGIN = "ROUTE_LOGIN";
    static ROUTE_CREATE_COURSE = "ROUTE_CREATE_COURSE";
    static ROUTE_UPLOAD_VIDEO = "ROUTE_UPLOAD_VIDEO";
    static ROUTE_COURSE_DETAILS = "ROUTE_COURSE_DETAILS";
}
