import { StyleSheet } from "react-native";
import { dark } from "../../constants/themes/dark";

export const cardStyles = StyleSheet.create({
    card: {
        shadowRadius: 10,
        shadowOffset: { width: -1, height: 1 },
        margin: 8,
        minWidth: "40%",
        marginRight: 20,
        backgroundColor: dark.Opacity.darkBlue1,
        textAlign: "center",
    },
    cardChoicesRight: {
        margin: 8,
        minHeight: 40,
        width: "40%",
        backgroundColor: dark.Opacity.darkGreen,
        borderColor: dark.theme.darkGreen,
        borderWidth: 5,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
    },
    cardChoicesResultRight: {
        minHeight: 40,
        height: "100%",
        width: "100%",
        backgroundColor: dark.Opacity.darkGreen,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
    },
    cardChoicesResultWrong: {
        minHeight: 40,
        height: "100%",
        width: "100%",
        backgroundColor: dark.Opacity.pink,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
    },
    cardChoicesResultSelected: {
        margin: 8,
        minHeight: 40,
        width: "40%",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
        borderColor: "white",
        borderWidth: 2,
        shadowRadius: 10,
        shadowColor: "white",
        shadowOpacity: 0.5,
    },
    cardChoicesSelect: {
        margin: 8,
        minHeight: 40,
        width: "40%",
        backgroundColor: dark.Opacity.darkBlue1,
        borderColor: dark.Opacity.darkBlue1,
        borderWidth: 5,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
    },
    cardChoicesNotSelect: {
        margin: 8,
        minHeight: 40,
        width: "40%",
        borderColor: dark.Opacity.invisible,
        borderWidth: 5,
        flexDirection: "row",
        justifyContent: "center",
        color: "white",
    },
    cardChoicesWrong: {
        minHeight: 40,
        margin: 8,
        width: "40%",
        backgroundColor: dark.Opacity.pink,
        borderColor: dark.theme.pink,
        borderWidth: 5,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        color: "white",
    },
    cardChoiceNumericWrong: {
        color: "white",
        backgroundColor: dark.Opacity.pink,
        padding: 16,
    },
    cardChoiceNumericRight: {
        color: "white",
        backgroundColor: dark.Opacity.darkGreen,
        padding: 16,
    },
    cardHeader: {
        margin: 8,
        marginLeft: 16,
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
        textAlignVertical: "center",
    },
    break: {
        backgroundColor: "white",
        opacity: 0.5,
        height: 1,
        marginTop: 1,
    },
    textChoice: {
        color: "white",
        fontSize: 20,
    },
});
